try:
    ans = 10 / 0
    print(ans)
except:
    print('Exception occurred in division')
    
    
print('Out of try-except block')

try:
    name = 'Chinmay'
    print(name[100])
except:
    print('Exception occurred')